# Generated by Django 4.0.4 on 2022-05-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctorreg',
            fields=[
                ('Did', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=20)),
                ('Hid', models.IntegerField()),
                ('Department', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=10)),
                ('Time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='hospitalreg',
            fields=[
                ('Hid', models.IntegerField(primary_key=True, serialize=False)),
                ('Hname', models.CharField(max_length=30)),
                ('Place', models.CharField(max_length=25)),
                ('Address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Contact', models.IntegerField()),
            ],
        ),
    ]
