# Generated by Django 4.0.4 on 2022-05-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctorreg_hospitalreg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingform',
            name='ContactNo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hospitalreg',
            name='Contact',
            field=models.CharField(max_length=10),
        ),
    ]
